### ISSUE TITLE
What happened to the velocity plots?

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/repository-dashboard-shiny#2]

**Comment by benneely** [comment]
In the last commit, we updated the data structures to display graphs beyond the end of a sprint deadline - this rendered the velocity line data invalid. Updated server.R to include valid velocity line data (beyond the end of a sprint deadline). Velocity lines are now visible. The current sprint view only shows the current velocity line to where data is available - can modify to extend if desired.
